name: Multi-Daily GitHub Contributions

on:
  schedule:
    - cron: "0 */2 * * *" # Runs every 2 hours
  workflow_dispatch: # Allow manual trigger

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make a dummy change
        run: |
          # Append timestamp so every commit is unique
          echo "Auto update at $(date -u)" >> update_log.txt

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add update_log.txt
          git commit -m "chore: auto-update at $(date -u)" || echo "No changes to commit"
          git push
